version: '3'
services:
  
  portfolio-client:
    image: portfolio-client
    container_name: portfolio-client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:80
    networks:
      - portfolio

networks:
  portfolio:
    name: portfolio
    driver: bridge